Feature/lab2 steps
ArctiqTeam/arctiq-copilot-trail pull request #18
Opened 2024-12-17 20:04 UTC by mh-iq

This pull request includes several enhancements to the `GameState` class in the `chessweb-cs` project and updates to the documentation for lab 2 development use cases. The most important changes include adding XML documentation comments to the `GameState` class, creating diagrams for the chess application, and updating the lab documentation to include prerequisites and detailed steps for using GitHub Copilot.

Enhancements to `GameState` class:

* [`chessweb-cs/Models/GameState.cs`](diffhunk://#diff-e3c5a4bd9b27baf0295b4afc4c06610b4e0d7537154ab0689962e359b78c9bf6L1-R40): Added XML documentation comments to properties and methods to improve code readability and maintainability. [[1]](diffhunk://#diff-e3c5a4bd9b27baf0295b4afc4c06610b4e0d7537154ab0689962e359b78c9bf6L1-R40) [[2]](diffhunk://#diff-e3c5a4bd9b27baf0295b4afc4c06610b4e0d7537154ab0689962e359b78c9bf6R49-R64) [[3]](diffhunk://#diff-e3c5a4bd9b27baf0295b4afc4c06610b4e0d7537154ab0689962e359b78c9bf6R98-R109)

Documentation improvements:

* [`labs/lab2-development-use-cases/Diagrams.md`](diffhunk://#diff-c5a010dcf42b74fcb97a365d90812c301cb28a6be5bf2b983185d24759348e34R1-R64): Added entity-relationship and state diagrams using Mermaid.js to visually represent the chess application components and their interactions.
* [`labs/lab2-development-use-cases/README.md`](diffhunk://#diff-f6ecbd14894d4548fd4bfca724a865db3616fecdcd58bcb2555afdaddc9a58adR5-R289): Updated the lab documentation to include prerequisites, detailed steps for using GitHub Copilot, and explanations of common problems and solutions when using Copilot.

2024-12-18 19:14 UTC, AXDOOMER requested changes

2024-12-18 19:14 UTC, AXDOOMER commented on labs/lab2-development-use-cases/README.md
> +Keep these practices in mind when submitting prompts to Copilot. You will see many of these issues.
One other thing that I do is say "output only the minimum amount of code needed to do this change" and it fixes the public code match even though it regenerates the same code.

2024-12-18 19:14 UTC, AXDOOMER commented on labs/lab2-development-use-cases/README.md
> +- In terms of documentation, Copilot can relieve a lot of tedium. Copilot can generate documenation for you and it can adopt your particular style of documentation given enough examples to work from.
It means the same but I've never seen somebody use "tedium" before.
```suggestion
- In terms of documentation, Copilot can relieve a lot of tediousness. Copilot can generate documentation for you and it can adopt your particular style of documentation given enough examples to work from. So write a few comments yourself and Copilot will resume in a consistent way. The special command for this activity is `/doc`.
```

2024-12-18 19:14 UTC, AXDOOMER commented on labs/lab2-development-use-cases/README.md
> +- This sample application is far from a complete Chess-playing interface. In fact, all it does is to provide a view of a Chess board that allows turn-based moves to be entered with very basic piece r
```suggestion
- This sample application is far from a complete Chess-playing interface. In fact, all it does is to provide a view of a chessboard that allows turn-based moves to be entered with very basic piece rules applied. It serves as a basis for extension using Copilot. If you don't have knowledge of or interest in Chess, don't worry, no expertise is required to participate in this part.
```

2024-12-18 19:14 UTC, AXDOOMER commented on labs/lab2-development-use-cases/README.md
> +- In this view we can see a familiar Chess board with pieces set up for the beginning of a game. There is a button that can be used to reset the position. The board is labeled on the ranks and files:
```suggestion
- In this view we can see a familiar chessboard with pieces set up for the beginning of a game. There is a button that can be used to reset the position. The board is labeled on the ranks and files: ranks are labeled 1-8 and files are labeled a-h. Finally, there is a turn indicator to the right of the board that will display which side and which colour is due to play.
```

2024-12-18 19:14 UTC, AXDOOMER commented on labs/lab2-development-use-cases/README.md
> +    input box below the chess board with the current FEN string of the board
```suggestion
    input box below the chessboard with the current FEN string of the board 
```

2024-12-18 21:47 UTC, mh-iq commented on labs/lab2-development-use-cases/README.md
> +- It can happen that Copilot does not start or provide an answer when it seems clear to the user that they are pausing for a suggestion. This happens most often in the inline copilot suggester. The s
good catch. I like the suggestion

2024-12-18 21:50 UTC, mh-iq commented on labs/lab2-development-use-cases/README.md
> +Keep these practices in mind when submitting prompts to Copilot. You will see many of these issues.
that's an interesting prompt, but it kinda sounds like a hack. We can mention that in the class, but I will leave it from the standard reference for now.

2024-12-18 21:57 UTC, mh-iq commented on labs/lab2-development-use-cases/README.md
> +- It can also happen that Copilot will regenerate the same content over and over again as if it has forgotten that it just gave that code. This is a form of hallucination error and does illustrate wh
We can mention this in the session, but I will leave that example out for now.

2024-12-20 17:57 UTC, peterv-arctiq approved these changes

2024-12-20 21:43 UTC, AXDOOMER approved these changes

2024-12-20 21:45 UTC, merged